[package]
edition = "2021"
name = "libew-demo"
version = "0.1.0"

[[bin]]
name = "demo"
path = "demo.rs"

[dependencies]
base64 = "0.22"
bitcoin = { version = "0.32", features = ["serde"] }
hex = "0.4"
serde_json = "1.0"
