[package]
edition = { workspace = true }
name = "repository"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }

# path dependencies
bdk_utils = { workspace = true }
database = { workspace = true }
types = { workspace = true }

[dev-dependencies]
external_identifier = { workspace = true }
http_server = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
ulid = { workspace = true }

[features]
account = ["types/account"]
all = [
  "account",
  "consent",
  "encrypted_attachment",
  "privileged_action",
  "recovery",
  "screener",
]
consent = ["types/consent"]
encrypted_attachment = ["types/account", "types/encrypted_attachment"]
privileged_action = ["types/privileged_action"]
recovery = ["types/recovery"]
screener = ["types/screener"]

[lints]
workspace = true
