address = "0.0.0.0"
cmkId = "fake"
customerKeysTableName = "wsm_customer_keys"
dekTableName = "wsm_deks"
dynamodbEndpoint = "http://dynamodb:8000"
enclaveEndpoint = "http://wsm-enclave:8080"
kmsProxyPort = 1000
runMode = "test"
