[package]
edition = { workspace = true }
name = "teltra"
publish = { workspace = true }
version = { workspace = true }

[dependencies]
teltra-sys = { path = "../teltra-sys" }
thiserror = { workspace = true }

[dev-dependencies]
hex = "0.4"
