[package]
edition = { workspace = true }
name = "authn_authz"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = "9.2.0"
jwt-authorizer = { workspace = true }
once_cell = { workspace = true }
secp256k1 = { version = "0.27.0", features = ["bitcoin_hashes", "serde"] }
serde = { workspace = true }
sha2 = "0.10.8"
tracing = { workspace = true }
utoipa = { workspace = true }
wsm-rust-client = { workspace = true }

# path dependencies
account = { workspace = true }
bdk_utils = { workspace = true }
errors = { workspace = true }
http_server = { workspace = true }
instrumentation = { workspace = true }
types = { workspace = true, features = ["account", "authn_authz"] }
userpool = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tower = { workspace = true }

[lints]
workspace = true
