manifest_version: {{manifest_version}}
fwup_bundle:
  product: {{product}}
  version: {{version}}
  assets:
{% if include_bootloader %}
    bootloader:
      image:
        name: {{bootloader_name}}.signed.bin
      signature:
        name: {{bootloader_name}}.detached_signature
{% endif %}
    application_a:
      image:
        name: {{application_a_name}}.signed.bin
      signature:
        name: {{application_a_name}}.detached_signature
    application_b:
      image:
        name: {{application_b_name}}.signed.bin
      signature:
        name: {{application_b_name}}.detached_signature
  parameters:
    wca_chunk_size: {{fwup_params.chunk_size}}
    signature_offset: {{fwup_params.signature_offset}}
    app_properties_offset: {{fwup_params.app_props_offset}}
