[package]
edition = { workspace = true }
license = "MIT"
name = "aws-vsock-http"
publish.workspace = true
version = "0.1.0"

[dependencies]
aws-smithy-runtime-api = { version = "1.8.1", features = ["client"] }
aws-smithy-types = "1.3.2"
bytes = "1.0"
http = { workspace = true }
http-body-util = "0.1.0"
hyper = { version = "1.6.0", features = ["client", "http1", "http2"] }
hyper-util = { version = "0.1", features = [
  "client",
  "client-legacy",
  "http1",
  "http2",
  "service",
  "tokio",
] }
nix = { version = "0.29", features = ["fs", "poll", "socket"] }
rustls = "=0.23.32"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = "=0.26.1"
tower = { workspace = true }
