[package]
edition = { workspace = true }
name = "bdk_utils"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
bdk = { workspace = true, features = ["electrum", "keys-bip39", "std"] }
feature_flags = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

# path dependencies
errors = { workspace = true }
metrics = { workspace = true }
