[package]
edition = { workspace = true }
name = "comms_verification"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
argon2 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }

# path dependencies
account = { workspace = true }
errors = { workspace = true }
notification = { workspace = true }
types = { workspace = true, features = ["account"] }
