[package]
edition = { workspace = true }
name = "screener"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = "1.17.0"
csv = "1.3.0"
s3-utils = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

errors = { workspace = true }
repository = { workspace = true, features = ["screener"] }
types = { workspace = true, features = ["account"] }

[dev-dependencies]
database = { workspace = true }
http_server = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
