[build]
target-dir = "_build/rust/target"

[target.'cfg(target_os = "android")']
rustflags = [
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=16384",
    "-C", "link-arg=-z",
    "-C", "link-arg=common-page-size=16384"
]
