flash:
  size: 2048K
  origin: 0x08000000
  alignment: 16
  partitions:
    # Bank 1: 0x08000000 - 0x080FFFFF
    - name: bootloader
      size: 128K
      sections:
        - name: program
          permissions: rwx
          target: loader
        - name: metadata
          size: 1K
          permissions: r
        - name: codesign_signature
          size: 64
          permissions: r
    - name: application_a
      size: 896K
      sections:
        - name: metadata
          size: 1K
          permissions: r
        - name: properties
          size: 512
          permissions: r
        - name: program
          permissions: rwx
          target: app-a
        - name: codesign_signature
          size: 64
          permissions: r
    # Bank 2: 0x08100000 - 0x081FFFFF
    - name: application_b
      size: 896K
      sections:
        - name: metadata
          size: 1K
          permissions: r
        - name: properties
          size: 512
          permissions: r
        - name: program
          permissions: rwx
          target: app-b
        - name: codesign_signature
          size: 64
          permissions: r
    - name: filesystem
      size: 128K
      permissions: rw
ram:
  origin: 0x20000000
  size: 768K
  partitions:
    - name: ram_noinit
      size: 256
      permissions: rwx
    - name: ram
      size: 786176
      permissions: rwx
sram4:
  origin: 0x28000000
  size: 16K
  partitions:
    - name: sram4
      size: 16K
      permissions: rwx
